added newb

diff --git a/bin/qad b/bin/qad
--- a/bin/qad
+++ b/bin/qad
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 dashless=$(basename "$0" | sed -e 's/-/ /')
-USAGE="USAGE: $dashless <branch>"
+USAGE="USAGE: $dashless [--commit <message>] <branch>"
 
 usage() 
 {
@@ -11,8 +11,39 @@ usage()
 
 echo_stage()
 {
-  echo "== $1 =="
+  echo "== \033[1;37m$1\033[0m =="
 }
+
+while test $# -ne 0
+do
+  case "$1" in
+  --commit)
+    case "$2" in '') usage ;; esac
+    commit_message="$2"
+    shift
+    ;;
+  --commit=*)
+    commit_message="$1"
+    shift
+    ;;
+  --user)
+    case "$2" in '') usage ;; esac
+    user="-u $2"
+    shift
+    ;;
+  --)
+    shift
+    break
+    ;;
+  -*)
+    usage
+    ;;
+  *)
+    break
+    ;;
+  esac
+  shift
+done
 
 branch_name=$1
 upstream_url=$(git config remote.upstream.url) 
@@ -33,13 +64,19 @@ if [[ $ec != 0 ]] ; then
     exit $ec
 fi
 
-echo_stage "Checking out $branch_name"
+echo_stage "Checking uncommitted changes in $branch_name"
 git diff-index --quiet HEAD
 ec=$?
 if [[ $ec != 0 ]] ; then
-	echo "There are uncommitted changes in branch: $branch_name"
-	echo "Cannot deploy!"
+  if ! test -z "$commit_message"; then
+    git add .
+    git add -u
+    git commit -m "\"$commit_message\""
+  else
+    echo "There are uncommitted changes in branch: $branch_name"
+    echo "Cannot deploy!"
     exit $ec
+  fi
 fi
 
 echo_stage "Checking out QA"
@@ -78,4 +115,7 @@ if [[ $ec != 0 ]] ; then
 fi
 
 echo_stage "Deploying to QA"
-fab -u tim -f deploy/fabfile.py deploy
+`fab $user -f deploy/fabfile.py deploy`
+
+echo_stage "Checking out $branch_name"
+git checkout "$branch_name"
